name: Deploy Android APK
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build & Release Secure APK
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Cache Gradle build
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            android/.gradle
            /usr/local/lib/android/sdk/cmake
            /usr/local/lib/android/sdk/ndk
          key: ${{ runner.os }}-gradle-v4-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-v4-

      - name: Cache Pub packages
        uses: actions/cache@v4
        with:
          path: |
            ${{ env.PUB_CACHE }}
            ~/.pub-cache
          key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pub-

      - name: Get Dependencies
        run: flutter pub get

      - name: Build Signed Release APK
        env:
          KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        run: |
          # Build APK which implicitly decodes keystore in build.gradle.kts
          flutter build apk --release --split-per-abi --target-platform android-arm64
          # Delete keystore traces after secure build
          rm -f android/app/mexapresta-release.jks

      - name: Auto-bump version
        id: version
        run: |
          CURRENT=$(grep '^version:' pubspec.yaml | sed 's/version: //' | sed 's/+.*//')
          NEW_VERSION="$CURRENT+${{ github.run_number }}"
          echo "VERSION=$NEW_VERSION" >> $GITHUB_OUTPUT

      - name: Create GH Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: "v${{ steps.version.outputs.VERSION }}"
          name: "MexaPresta v${{ steps.version.outputs.VERSION }}"
          body: "Compilación de producción firmada con clave de seguridad v${{ steps.version.outputs.VERSION }}"
          files: build/app/outputs/flutter-apk/app-arm64-v8a-release.apk
          make_latest: true
